# Generated by Django 4.1.4 on 2022-12-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
