# Generated by Django 4.1.4 on 2022-12-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
