# Generated by Django 4.1.4 on 2022-12-10 01:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='corpo_do_texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
