# Generated by Django 4.1.4 on 2023-01-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagem_do_pedido',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
