# Generated by Django 4.1.4 on 2023-01-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pedido_imagem_do_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='imagem_do_pedido',
            new_name='imagem',
        ),
    ]
