# Generated by Django 4.1.4 on 2023-01-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_imagem_do_pedido_pedido_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='imagem',
        ),
    ]
