# Generated by Django 4.1.4 on 2023-01-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_pedido_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
