# Generated by Django 4.1.6 on 2023-02-04 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_pedido_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=180)),
                ('rua', models.CharField(max_length=180)),
                ('bairro', models.CharField(max_length=180)),
                ('numero', models.CharField(max_length=180)),
                ('cidade', models.CharField(max_length=180)),
                ('complemento', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
