# Generated by Django 4.1.6 on 2023-02-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='nomeCompleto',
            new_name='nome_Completo',
        ),
    ]
